version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./wellth_water:/wellth_water
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=wellth_water_db
      - DB_USER=wellth_water
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTRGRES_DB=wellth_water_db
      - POSTRGRES_USER=wellth_water
      - POSTRGRES_PASSWORD=password
